name: day_picker
description: A Flutter widget library which helps us to select days in a week.
version: 2.1.0
author: Shan Shaji <shanshaji224@gmail.com>
homepage: https://github.com/shan-shaji/day_picker

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
